### ISSUE TITLE
UPW API, problem with filter

### ISSUE THREAD

**Issue by boer0107-zz** [OAmonitor/OAmonitor#14]
I get the following error message when running get_upw. I have already tried rerun a previous project (which did not have this error then) and I have also tried to reinstall (remotes::install_github("https://github.com/bvreede/OAmonitor")). Both did not solve the issue.

Note that it only returns an error message after two minutes. It does return a file (upw_from_doi_2021-04-06), however this file is empty.

`> get_upw(df, source = "api", email = "j.deboer@uu.nl", save_results = T)
Mining the upw api on 1078 items.
This will take around 12 minutes. (Current time is 2021-04-06 12:11:49.)
Done mining the upw api at 2021-04-06 12:13:45.
Error: Problem with `filter()` input `..1`.
x object 'doi' not found
i Input `..1` is `!duplicated(doi)`.
Run `rlang::last_error()` to see where the error occurred.
> rlang::last_error()
<error/dplyr_error>
Problem with `filter()` input `..1`.
x object 'doi' not found
i Input `..1` is `!duplicated(doi)`.
Backtrace:
  1. OAmonitor::get_upw(...)
  9. base::.handleSimpleError(...)
 10. dplyr:::h(simpleError(msg, call))
Run `rlang::last_trace()` to see the full context.
> rlang::last_trace()
<error/dplyr_error>
Problem with `filter()` input `..1`.
x object 'doi' not found
i Input `..1` is `!duplicated(doi)`.
Backtrace:
     x
  1. +-OAmonitor::get_upw(...)
  2. | \-df %>% dplyr::filter(!duplicated(doi))
  3. +-dplyr::filter(., !duplicated(doi))
  4. +-dplyr:::filter.data.frame(., !duplicated(doi))
  5. | \-dplyr:::filter_rows(.data, ...)
  6. |   +-base::withCallingHandlers(...)
  7. |   \-mask$eval_all_filter(dots, env_filter)
  8. +-base::duplicated(doi)
  9. \-base::.handleSimpleError(...)
 10.   \-dplyr:::h(simpleError(msg, call))`

**Comment by bmkramer** [comment]
(I'm looking into this now)

**Comment by bmkramer** [comment]
Unpaywall stopped support of API v1, so we pushed support for API v2 to the main branch. This should now work.

**Comment by bmkramer** [comment]
As a side note, using Unpaywall v2 allows detection of cases where a doi is labeled Bronze OA by Unpaywall (i.e. article in hybrid or closed journal that is available on publisher website but without license), but also found in one or more repositories. These can now be labeled green OA. 

This has not yet been implemented (it's in the code already, but currently suppressed), but we would like to do so as it increases the proportion of OA that is detected. 

It would mean, though, that rerunning a sample would result in a higher % of green OA.
Would this be a problem at this point in time?

**Comment by boer0107-zz** [comment]
I have run the OAmonitor and it is working again.
I have compared results with the output from API v1 (date: March 24th 2021) with output from API v2 (date: April 22nd 2021) for the same dataset. There is a minor increase in OA availability, from 68.6% to 69.0%. This can be attributed to the new API, but also because of the month that has passed between the two runs in which embargo dates might have expired. I haven't investigated this further.
