### ISSUE TITLE
Modify Unpaywall OA colour precedence so that Green goes before Bronze

### ISSUE THREAD

**Issue by kmhettne** [OAmonitor/OAmonitor#4]
To assign an OA color to an article, Unpaywall calculate the OA colors of each available location as if it were the only one. Then Unpaywall takes the best one, the order of precedence being gold > hybrid > bronze > green. So if an article is Bronze because there is a publisher-hosted copy that would be Bronze on its own.

We need to add a function that checks the top-level API for the `has_repository_copy` attribute. That can tell us if there is a would-be Green location.

**Comment by bmkramer** [comment]
Implemented, together with switch to querying UPW API v2
