### ISSUE TITLE
DOAJ API: bibjson.identifier

### ISSUE THREAD

**Issue by boer0107-zz** [OAmonitor/OAmonitor#9]
The DOAJ API does not work anymore:

Error: Can't subset columns that don't exist.
x Column `bibjson.identifier` doesn't exist.

Backtrace:
  1. OAmonitor::get_doaj(df, source = "api", save_results = F)
  2. OAmonitor:::api_to_df(., "doaj")
 10. OAmonitor:::process_doaj(.)
 11. tidyr::unnest(., bibjson.identifier, keep_empty = T, names_sep = "_")
 20. tidyselect::eval_select(enquo(cols), data)
 21. tidyselect:::eval_select_impl(...)
 29. tidyselect:::vars_select_eval(...)
 30. tidyselect:::walk_data_tree(expr, data_mask, context_mask)
 31. tidyselect:::as_indices_sel_impl(...)
 32. tidyselect:::as_indices_impl(x, vars, strict = strict)
 33. tidyselect:::chr_as_locations(x, vars)
 34. vctrs::vec_as_location(x, n = length(vars), names = vars)
 36. vctrs:::stop_subscript_oob(...)
 37. vctrs:::stop_subscript(...)

**Comment by bvreede** [comment]
Thanks for updating us! The DOAJ-API updated; @bmkramer is working on the patch. Stay tuned!

**Comment by boer0107-zz** [comment]
Okay, keep me updated. I have two pending requests for which I need the workflow (no hurry though).

**Comment by bmkramer** [comment]
I'll try to get this done quickly though :)

Op wo 2 dec. 2020 om 13:50 schreef boer0107 <notifications@github.com>:

**Comment by boer0107-zz** [comment]
Issue has already been solved. Close issue?

**Comment by bmkramer** [comment]
Yes, thanks for the reminder to close :-)

**Comment by bmkramer** [comment]
Implemented
